Rails:
  Enabled: true

AllCops:
  Exclude:
    - 'Gemfile'
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'spec/spec_helper.rb'
    - 'test/spec_helper.rb'
#    - 'spec/teaspoon_env.rb'
    - 'vendor/**/*'
    - 'lib/tasks/display-coverage.rake'

Metrics/AbcSize:
  Max: 27

# Because the home page spec has a lot to test.
Metrics/BlockLength:
  Exclude:
    - 'spec/features/home_page_spec.rb'

Metrics/ClassLength:
  Max: 120

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 15

Metrics/ModuleLength:
  Max: 120

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/FrozenStringLiteralComment:
  Enabled: false

Lint/HandleExceptions:
  Enabled: false
